Repository naFila-pt/nafila, pull requests merged in 2020-05, with the labels that each got.

#95 fix: max-length for store name
  src/pages/Admin/SignUp/SignUp.js
Labels: Status: Ready To Review, Type: Hotfix

#97 refactor: lock dependencies and cleanup code
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/production.yml
  .gitignore
  .prettierrc
  README.md
  docs/frontend.md
  docs/serverless.md
  firebase.json
  functions/index.js
  package.json
  public/favicon-114x114.png
  public/favicon-120x120.png
  public/favicon-128x128.png
  public/favicon-144x144.png
  public/favicon-152x152.png
  public/favicon-16x16.png
  public/favicon-180x180.png
  public/favicon-192x192.png
  public/favicon-32x32.png
  public/favicon-384x384.png
  public/favicon-512x512.png
  public/favicon-57x57.png
  public/favicon-60x60.png
  public/favicon-72x72.png
  public/favicon-76x76.png
  public/favicon-96x96.png
  public/favicon.ico
  public/favicon.svg
  public/index.html
  public/logo192.png
  public/manifest.json
  src/index.css
  src/pages/Admin/AddConsumer/AddConsumerName.js
  src/pages/Admin/AddConsumer/AddConsumerPhone.js
  src/pages/Admin/EndQueue/EndQueue.js
  src/pages/Admin/Queue/Manage/Manage.js
  src/pages/HomeContent/TermsConditions.js
  src/pages/TicketContent/Leave.js
  tools/test-functions.js
  yarn.lock
Labels: Status: Ready To Review, Type: Refactor

#96 Add meta tags to use open graph
  docs/serverless.md
  public/index.html
  public/shareable_image.png
Labels: Status: Changes Requested, Type: Feature

#100 - Remove mail and add sms on onboarding layouts
  src/assets/icons/human-onboarding-left.svg
  src/assets/icons/human-onboarding-right.svg
  src/assets/icons/site_icon.svg
  src/components/OnBoardingLayout/Admin/DesktopLayout.js
  src/components/OnBoardingLayout/Admin/MobileLayout.js
  src/i18n.js
Labels: Status: Ready To Review, enhancement

#99 ticketstatus - fix botao sair nafila
  src/pages/TicketStatus/TicketStatus.js
Labels: Status: Ready To Review, bug

#102 remove email signup option and change it to sms instead
  src/assets/icons/icon_tlm_big.svg
  src/components/Button/Button.js
  src/components/ConsumerTicket/ConsumerTicket.js
  src/i18n.js
  src/pages/TicketContent/Ticket.js
  src/pages/TicketStatus/TicketStatus.js
Labels: Status: Ready To Review, enhancement

#101 Analytics grouping per company group
  README.md
  docs/serverless.md
  functions/index.js
  package.json
  src/components/App/App.js
  src/components/EmptyState/EmptyState.js
  src/components/OnBoardingLayout/Admin/DesktopLayout.js
  src/components/OnBoardingLayout/Admin/MobileLayout.js
  src/components/OnBoardingLayout/OnBoardingLayoutDesktop.js
  src/components/OnBoardingLayout/OnBoardingLayoutMobile.js
  src/components/TitleComponent/TitleComponent.js
  src/components/TitleComponent/index.js
  src/pages/Admin/AddConsumer/AddConsumer.js
  src/pages/Admin/AddConsumer/AddConsumerName.js
  src/pages/Admin/AddConsumer/AddConsumerPhone.js
  src/pages/Admin/AddConsumer/AddConsumerSuccess.js
  src/pages/Admin/EndQueue/EndQueue.js
  src/pages/Admin/EndQueue/EndQueueSuccess.js
  src/pages/Admin/Home/Home.js
  src/pages/Admin/Login/Login.js
  src/pages/Admin/PreQueue/PreQueue.js
  src/pages/Admin/Queue/Manage/Manage.js
  src/pages/Admin/Queue/Queue.js
  src/pages/Admin/Queue/Start/Start.js
  src/pages/Admin/RecoverPassword/RecoverPassword.js
  src/pages/Admin/RecoverPassword/RecoverPasswordSuccessful.js
  src/pages/Admin/SignUp/SignUp.js
  src/pages/Admin/SignUp/SuccessfulSignUp.js
  src/pages/Admin/WelcomePanel/WelcomePanel.js
  src/pages/HomeContent/Home.js
  src/pages/HomeContent/TermsConditions.js
  src/pages/QueuePoster/QueuePoster.js
  src/pages/TicketContent/Leave.js
  src/pages/TicketContent/Ticket.js
  src/pages/TicketStatus/TicketStatus.js
  yarn.lock
Labels: Status: Ready To Review, enhancement
